---
# Remove ETCD on VMware VM Playbook


################################################################### REMOVE ETCD
- name: "Uninstall ETCD"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: yes
  vars:
    create_user_name: "{{ etcd_user_name }}"
    create_group_name: "{{ etcd_user_group }}"
  roles:
    - role: "etcd/etcd-remove"
  #  - role: "user/user-delete"
  #  - role: "user/group-delete"


####################################################################### ETCDCTL
- name: "Remove etcdcli on {{ admin_hostname }}"
  hosts: ["admin"]
  become: yes
  gather_facts: false
  roles:
    - role: "etcd/etcd-client-remove"
