---
# ETCD install for k8s on VMware VM Playbook
# 
# 5 ETCD
# 2 LB with VIP for ETCD Client

########################################################################## INIT
- name: "Get IP from ETCD nodes"
  hosts: ["admin","etcd_lb_physical","etcd_nodes"]
  become: yes
  gather_facts: true
  roles:
    #- role: "system/nala/nala-update"
    #- role: "system/nala/nala-upgrade"


###################################################################### HA-PROXY
- name: "Load balancer installation"
  hosts: ["etcd_lb_physical"]
  become: false
  gather_facts: false
  roles:
    #- role: "haproxy/haproxy-install"
    #- role: "keepalived/keepalived-install"


################################################################### DELETE ETCD
- name: "Uninstall ETCD"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: yes
  vars:
    create_user_name: "{{ etcd_user_name }}"
    create_group_name: "{{ etcd_user_group }}"
  roles:
  #  - role: "etcd/etcd-delete"
  #  - role: "user/user-delete"
  #  - role: "user/group-delete"

############################################################## CREATE ETCD USER
- name: "Create ETCD users for all nodes"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: false
  vars:
    create_group_name: "{{ etcd_user_group }}"
    create_group_gid: "{{ etcd_user_gid }}"
    create_group_system: true
    create_user_name: "{{ etcd_user_name }}"
    create_user_uid: "{{ etcd_user_uid }}"
    create_user_comment: "{{ etcd_user_comment }}"
    create_user_shell: "/sbin/nologin"
    create_user_system: true
  roles:
  #  - role: "user/group-create"
  #  - role: "user/user-create"

################################################################ LAUNCH INSTALL
- name: "Copy nodes certificates and install ETCD"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: yes
  roles:
    - role: "etcd/etcd-install"

####################################################################### ETCDCTL
- name: "Install etcdcli on {{ admin_hostname }}"
  hosts: ["admin"]
  become: yes
  gather_facts: false
  roles:
    - role: "etcd/etcd-client-install"
