---
# ETCD install with TLS for k8s on VMware VM Playbook
# 
# 5 ETCD
# 2 LB with VIP for ETCD Client

########################################################################## INIT
- name: "Get IP from ETCD nodes"
  hosts: ["admin","sub-ca","etcd_lb_physical","etcd_nodes"]
  become: yes
  gather_facts: true
#  roles:
    #- role: "system/nala/nala-update"
    #- role: "system/nala/nala-upgrade"

###################################################################### HA-PROXY
- name: "Load balancer installation"
  hosts: ["etcd_lb_physical"]
  become: false
  gather_facts: false
  roles:
    #- role: "haproxy/haproxy-install"
    #- role: "keepalived/keepalived-install"

############################################################## CREATE ETCD USER
- name: "Create ETCD users for all nodes"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: false
  vars:
    create_group_name: "{{ etcd_user_group }}"
    create_group_gid: "{{ etcd_user_gid }}"
    create_group_system: true
    create_user_name: "{{ etcd_user_name }}"
    create_user_uid: "{{ etcd_user_uid }}"
    create_user_comment: "{{ etcd_user_comment }}"
    create_user_shell: "/sbin/nologin"
    create_user_system: true
  roles:
  #  - role: "user/group-create"
  #  - role: "user/user-create"


################################################################## CREATE CERTS
- name: "Create passphrase file and CA"
  hosts: ["sub-ca"]
  become: yes
  gather_facts: false
  vars_prompt:
  - name: openssl_secret_passphrase
    prompt: Sub CA certificate passphrase
  vars:
    openssl_hosts: "{{ groups['etcd_nodes'] }}"
    openssl_certificate_names: ["server"]
    openssl_certificate_type: "server"
    openssl_destination_directory: "{{ openssl_sub_directory }}"
    openssl_passfile: "{{ openssl_sub_passfile }}"
  roles:
    - role: "system/openssl/openssl-passfile-create"
    - role: "system/openssl/openssl-create-key"
    - role: "system/openssl/openssl-create-csr"
    - role: "system/openssl/openssl-create-crt"
    - role: "system/openssl/openssl-pull-certs"
    
############################################################ CLIENT CERTIFICATE
- name: "Create server certificates for {{ admin_hostname }} member"
  hosts: ["sub-ca"]
  become: yes
  gather_facts: false
  vars:
    openssl_hosts: "{{ admin_hostname }}"
    openssl_certificate_names: ["etcd-client"]
    openssl_certificate_type: "client"
    openssl_destination_directory: "{{ openssl_sub_directory }}"
    openssl_passfile: "{{ openssl_sub_passfile }}"
  roles:
    - role: "system/openssl/openssl-create-key"
    - role: "system/openssl/openssl-create-csr"
    - role: "system/openssl/openssl-create-crt"
    - role: "system/openssl/openssl-pull-certs"
    - role: "system/openssl/openssl-passfile-remove"
  

################################################################ LAUNCH INSTALL
- name: "Copy nodes certificates and install ETCD"
  hosts: ["etcd_nodes"]
  become: yes
  gather_facts: yes
  vars:
    openssl_certificate_names: ["server", "peer" ]
    openssl_remote_directory: "/etc/etcd/pki"
    openssl_remote_owner: "{{ etcd_user_name }}"
    openssl_remote_group: "{{ etcd_user_group }}"
    openssl_local_directory: "/home/{{ admin_username }}/ca"
  roles:
    - role: "system/openssl/openssl-push-certs"
    - role: "etcd/etcd-install-with-tls"

####################################################################### ETCDCTL
- name: "Install etcdcli on {{ admin_hostname }}"
  hosts: ["admin"]
  become: yes
  gather_facts: false
  vars:
    openssl_certificate_names: ["etcd-client"]
    openssl_remote_directory: "/home/{{ admin_username }}/.certs/etcd"
    openssl_remote_owner: "{{ ansible }}"
    openssl_remote_group: "{{ ansible }}"
    openssl_local_directory: "/home/{{ admin_username }}/ca"
  roles:
  - role: "system/openssl/openssl-push-certs"
  - role: "etcd/etcd-client-install-with-tls"
