---
# tasks file to remove etcd

################################################################# STOP SERVICE
- name: "Disable and remove etcd service"
  ansible.builtin.systemd:
    name: etcd
    state: stopped
    daemon_reload: yes
    masked: no
    enabled: false
    force: true

############################################################## REMOVE ALL FILES
- name: "Move the extracted ETCD executables to local bin"
  ansible.builtin.file:
    path: "{{ etcd_install_directory }}/{{ etcd_archive }}/{{ item }}"
    state: absent
  with_items:
    - etcd
    - etcdctl
    - etcdutl
    - /etc/etcd 
    - /var/lib/etcd
    - /etc/systemd/system/etcd.service