---
# tasks file for etcd-remove

################################################################# STOP SERVICE
- name: "Disable and remove etcd service"
  ansible.builtin.systemd:
    name: etcd
    state: stopped
    daemon_reload: yes
    masked: no
    enabled: false
    force: true

############################################################## REMOVE ALL FILES
- name: "Remove binaries"
  ansible.builtin.file:
    path: "/usr/local/bin/{{ item }}"
    state: absent
  with_items:
    - etcd
    - etcdctl
    - etcdutl

- name: "Remove folders"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/etcd 
    - /var/lib/etcd
    - /etc/systemd/system/etcd.service



